name = "my-biller-sync"
main = "src/index.ts"
compatibility_date = "2026-08-08"
workers_dev = true

[[durable_objects.bindings]]
name = "SHOP_DO"
class_name = "ShopDO"

[[ratelimits]]
name = "PAIR_RATE_LIMITER"
namespace_id = "2608091857"

[ratelimits.simple]
limit = 20
period = 60

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ShopDO"]
